version: "3.8"

services:
  fastapi_worker:
    build: .
    container_name: fastapi_worker
    ports:
      - "8000:8000"  # Mở cổng API
    environment:
      RABBITMQ_HOST: rabbitmq  # Kết nối đến RabbitMQ container
      RABBITMQ_QUEUE: test_queue
    depends_on:
      - rabbitmq  # Đảm bảo RabbitMQ chạy trước
    restart: always

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    ports:
      - "5672:5672"  # Cổng AMQP để Consumer kết nối
      - "15672:15672"  # Cổng quản lý RabbitMQ Web UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: always
