version: "3.8"

services:
  fastapi_worker:
    build: .
    container_name: fastapi_worker
    ports:
      - "8000:8000"  # Mở cổng API
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "192.168.132.250:9092"
      KAFKA_TOPIC: "news.crawler.request"
      KAFKA_GROUP_ID: "news-crawler-consumer"
    restart: always
