[supervisord]
nodaemon=true  ; Chạy foreground, không chạy dưới nền

[program:api]
command=uvicorn crawl_request:app --host 0.0.0.0 --port 8000
autostart=true
autorestart=true
stderr_logfile=/dev/stderr
stdout_logfile=/dev/stdout

[program:cronjob]
command=python cron_job.py
autostart=true
autorestart=true
stderr_logfile=/dev/stderr
stdout_logfile=/dev/stdout

[program:worker]
command=python worker.py
autostart=true
autorestart=true
stderr_logfile=/dev/stderr
stdout_logfile=/dev/stdout
