[supervisord]
nodaemon=true  ; Chạy foreground, không chạy dưới nền

[program:api]
command=uvicorn crawl_request:app --host 0.0.0.0 --port 8000
autostart=true
autorestart=true
stderr_logfile=/dev/stderr
stdout_logfile=/dev/stdout

[program:cronjob]
command=python cron_job.py
autostart=true
autorestart=true
stderr_logfile=/dev/stderr
stdout_logfile=/dev/stdout

[program:rabbitmq_consumer]
command=python rabbitmq_consumer.py  ; Chạy Worker lắng nghe RabbitMQ
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/rabbitmq_consumer.err.log
stdout_logfile=/var/log/supervisor/rabbitmq_consumer.out.log