# Tên báo muốn crawl [baodientudanviet ,tapchidoanhnghiepvatiepthi ,tapchidaututaichinh ,tapchinhadautu ,
# tapchisuckhoecongdong ,tapchidoanhnghiepvahoinhap ,tapchidoanhnghiepvietnam ,tapchithuonghieuvasanpham ,
# tapchidientutrithuc ,tapchimekongasean ,tapchidientugiaoducvietnam ,tapchichatluongcuocsong ,
# tapchidientukinhtechungkhoanvietnam ,tapchithoidai ,thoibaovanhocnghethuat ,baonhabaovacongluan ,
# tapchidientunhipsongthitruong ,tapchimotthegioi ,tapchidiendandoanhnghiep ,tapchidientunguoiduatin ,tapchilaodongcongdoan ,
# tapchibongda ,baotienphong ,trithucvacuocsong ,phunuvietnam ,baothanhnien ,nhandan ,baolaodong ,
# baodaidoanket ,vtv ,tapchikhoahocvacongnghe ,baokiemtoan ,tochucnhanuoc ,tapchixaydung ,baochinhphu ,
# baoquocte ,dantocmiennui ,tapchithongtinvatruyenthong ,tapchigiaothongvantai ,kinhtevadubao ,thethaovanhoa ,
# baodauthau ,dientutoquoc ,baohaiquanonline ,daibieunhandan ,nongnghiepmoitruong ,giaoducthoidai ,tapchithanhtra ,
# tapchibaohiemxahoi, tapchinganhang, thoibaonganhang ,tapchitaichinh,kiemsat,vov,congannhandan, baoxaydung, 
# suckhoedoisong, congly, congthuong, quanlythitruong, tapchigiaoduc, thuonghieuvaphapluat, kinhtedouong, 
# suckhoecong, vneconomy, thuonghieucongluan, taichinhdoanhnghiep, congnghevadoisong, phunumoi, 
# vietnamdaily, kienthuc, dangcongsan, tainguyenvamoitruong, tapchicongthuong, baohaiquanvietnam, 
#  thoibaotaichinhvietnam, thanhtra, baodantoc, baovephapluat, baotintuc, 
# baodautu, vtcnews, tapchidientu, vnexpress, vietnamnet, dantri, tapchitoaan, quandoinhandan, baovanhoa
# ]
webnames: ["vnexpress"]
# Có thể crawl theo url hoặc chuyên mục của báo
# tasks = ["url", "type"]
task: "type"

#Thông tin ghi log
logger_fpath: "logger/logger_config.yml"
urls_fpath: "urls.txt"
output_dpath: "result"
num_workers: 1

# Nếu task == "type" thì  article_type là chuyên mục báo or All types task == "all"
article_type: "all"
# Số page cần khi crawl
total_pages: 1
ui_hash_file: "./ui_hashes.json"
news_sites:
  vnexpress: "https://vnexpress.net"
  vietnamnet: "https://vietnamnet.vn/"
  dantri: "https://dantri.com.vn/"
  tapchitoaan: "https://tapchitoaan.vn/"
  quandoinhandan: "https://www.qdnd.vn/"
  baovanhoa: "https://baovanhoa.vn/"
  tapchidientu: "https://vietq.vn/"
  vtcnews: "https://vtcnews.vn/"
  baodautu: "https://baodautu.vn/"
  baotintuc: "https://baotintuc.vn/"
  baophapluat: "https://baovephapluat.vn/"
  baodantoc: "https://baodantoc.vn/"
  thanhtra: "https://thanhtra.com.vn/"
  thoibaotaichinhvietnam: "https://thoibaotaichinhvietnam.vn/"
  tapchicongthuong: "https://tapchicongthuong.vn/"
  tainguyenvamoitruong: "https://www.tainguyenvamoitruong.vn/"
  dangcongsan: "https://dangcongsan.vn/"
  kienthuc: "https://kienthuc.net.vn/"
  vietnamdaily: "https://vietnamdaily.kienthuc.net.vn/"
  phunumoi: "https://phunumoi.net.vn/"
  congnghevadoisong: "https://congnghevadoisong.vn/"
  taichinhdoanhnghiep: "https://taichinhdoanhnghiep.net.vn/"
  thuonghieucongluan: "https://thuonghieucongluan.com.vn/"
  vneconomy: "https://vneconomy.vn/"
  suckhoecong: "https://suckhoecong.vn/"
  kinhtedouong: "https://kinhtedouong.vn/"
  thuonghieuvaphapluat: "https://thuonghieuvaphapluat.vn/"
  tapchigiaoduc: "https://tapchigiaoduc.edu.vn/"
  quanlythitruong: "https://qltt.vn/"
  congthuong: "https://congthuong.vn/"
  congly: "https://congly.vn/"
  suckhoedoisong: "https://suckhoedoisong.vn/"
  baoxaydung: "https://baoxaydung.vn/"
  congannhandan: "https://cand.com.vn/"
  vov: "https://vov.vn/"
  kiemsat: "https://kiemsat.vn/"
  tapchitaichinh: "https://tapchitaichinh.vn/"
  thoibaonganhang: "https://thoibaonganhang.vn/"
  tapchinganhang: "https://tapchinganhang.gov.vn/"
  tapchibaohiemxahoi: "https://tapchibaohiemxahoi.gov.vn/"
  tapchithanhtra: "https://thanhtravietnam.vn/"
  giaoducthoidai: "https://giaoducthoidai.vn/"
  nongnghiepmoitruonng: "https://nongnghiepmoitruong.vn/"
  daibieunhandan: "https://daibieunhandan.vn/"
  haiquanonline: "https://haiquanonline.com.vn/"
  dientutoquoc: "https://toquoc.vn/"
  baodauthau: "https://baodauthau.vn/"
  thethaovanhoa: "https://thethaovanhoa.vn/"
  kinhtevadubao: "https://kinhtevadubao.vn/"
  tapchigiaothongvantai: "https://giaothong.tapchixaydung.vn/"
  tapchithongtinvatruyenthong: "https://ictvietnam.vn/"
  dantocmiennui: "https://dantocmiennui.baotintuc.vn/"
  vietnamplus: "https://www.vietnamplus.vn/"
  baoquocte: "https://baoquocte.vn/"
  baochinhphu: "https://baochinhphu.vn/"
  tapchixaydung: "https://tapchixaydung.vn/"
  tochucnhanuoc: "https://tcnnld.vn/"
  baokiemtoan: "http://baokiemtoan.vn/"
  tapchikhoahocvacongnghe: "https://vjst.vn/"
  vtv: "https://vtv.vn/"
  baodaidoanket: "https://baodaidoanket.vn/"
  baonhandan: "https://nhandan.vn/"
  baothanhnien: "https://thanhnien.vn/"
  phunuvietnam: "https://phunuvietnam.vn/"
  trithucvacuocsong: "https://kienthuc.net.vn/"
  # baotienphong: "https://tienphong.vn/"
  tapchibongda: "https://bongdaplus.vn/"
  # baolaodong: "https://baolaodong.vn/"
  tapchilaodongcongdoan: "https://laodongcongdoan.vn/"
  tapchidientunguoiduatin: "https://nguoiduatin.vn/"
  tapchidiendandoanhnghiep: "https://diendandoanhnghiep.vn/"
  tapchimotthegioi: "https://1thegioi.vn/"
  tapchidientunhipsongthitruong: "https://markettimes.vn/"
  baonhabaovacongluan: "https://congluan.vn/"
  thoibaovanhocnghethuat: "https://arttimes.vn/"
  tapchithoidai: "https://thoidai.com.vn/"
  tapchidientukinhtechungkhoanvietnam: "https://kinhtechungkhoan.vn/"
  tapchichatluongcuocsong: "https://chatluongvacuocsong.vn/"
  tapchidientugiaoducvietnam: "https://giaoduc.net.vn/"
  tapchimekongasean: "https://mekongasean.vn/"
  tapchidientutrithuc: "https://znews.vn/"
  tapchithuonghieuvasanpham: "https://thuonghieusanpham.vn/"
  tapchidoanhnghiepvietnam: "https://doanhnghiepvn.vn/"
  tapchidoanhnghiepvahoinhap: "https://doanhnghiephoinhap.vn/"
  tapchisuckhoecongdong: "https://suckhoecongdongonline.vn/"
  tapchinhadautuL: "https://nhadautu.vn/"
  tapchidaututaichinh: "https://vietnamfinance.vn/"
  tapchidoanhnghiepvatiepthi: "https://doanhnghieptiepthi.vn/"
  baodientudanviet: "https://danviet.vn/"
